#!/usr/bin/env bash
mkdir classes
javac -d classes/ src/com/CNSApplet.java
cp manifest.txt classes/
cd classes/
jar -cmvf manifest.txt cnsapplet.jar com
jar tvf cnsapplet.jar
chmod +x cnsapplet.jar
# keytool -genkey -keyalg rsa -keysize 1024 -alias cnsappletkey -validity 365 -keystore .keystore
jarsigner cnsapplet.jar cnsappletkey
jarsigner -verify -verbose -certs cnsapplet.jar
mv cnsapplet.jar ../
cd ..
rm -rf classes
